### ISSUE TITLE
Ok to move this jupyter/nbindex repo to the Jupyter Attic?

### ISSUE THREAD

**Issue by JamiesHQ** [jupyter/nbindex#2]
Hi @rgbkrk , 
Fernando & Brian suggested moving this repo to the Jupyter Attic. Let me know if that is ok with you. If it isn't Attic-able, it will become part of the purview of the team working on Services

Thanks!

**Comment by rgbkrk** [comment]
Definitely, go for it.

**Comment by JamiesHQ** [comment]
@rgbkrk cool beans. thanks!
